# Käytä Python 3.8 -pohjakuvaa
FROM python:3.8-slim

# Aseta työhakemisto
WORKDIR /app

# Asenna tarvittavat työkalut, kuten git, Tesseract ja OpenGL (OpenCV:tä varten)
RUN apt-get update && apt-get install -y \
    tesseract-ocr \
    libtesseract-dev \
    libgl1-mesa-glx \
    && rm -rf /var/lib/apt/lists/*

# Kopioi requirements-tiedosto konttiin
COPY requirements.txt .

# Asenna Python-riippuvuudet (PyTorchin ja muiden kirjastojen kanssa)
RUN pip install --no-cache-dir -r requirements.txt

# Kopioi Webtoon-translator-projektin tiedostot ja testidata konttiin
COPY . .

# Tarkista, että Bubbledetect.pt-malli on olemassa ja aseta sille oikeudet
RUN ls /app && chmod 644 /app/Bubbledetect.pt

# Aseta oletuskomento suorittamaan testit
CMD ["python", "-m", "unittest", "discover", "-s", "."]
